# Criado por Rodrigo Pelanza e Leandro Batista
version: '2.0'

services:

  mysql:
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: teste
    restart: always

  mongo:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      MONGODB_PASS: senha@123
    restart: always

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    ports:
      - "81:80"
    environment:
      MYSQL_ROOT_PASSWORD: teste
      PMA_HOST: mysql

  alertaweb:
    depends_on:
      - mongo
    image: alerta/alerta-web
    ports:
      - "80:80"
    environment:
      MONGO_URI: mongodb://mongo:27017/monitoring
    restart: always
