version: '3'

services:
  nginx:
    image: nginx:1.15.7
    container_name: proxy-reverso
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - rundeck:rundeck
      - jenkins:jenkins 

  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5000:5000"

  rundeck:
    container_name: rundeck
    image: rundeck/rundeck:3.0.8
    ports:
      - "4440:4440"
      - "4443:4443"
